development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ucms-dev
  pool: 5
  username: root
  password: 'our66070512'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ucms-test
  pool: 5
  username: root
  password: 'our66070512'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ucms
  pool: 5
  username: root
  password: 'our66070512'